#version: '3.1'
#
#services:
#
#  tgbot:
#    container_name: tgbot
#    build:
#      context: .
#    command: python app.py
#    networks:
#      - botnet
#    restart: always
#    env_file:
#      - ".env"
#    volumes:
#      - .:/src
#
#  igbot:
#    container_name: igbot
#    build:
#      context: ./IgSide
#    networks:
#      - ignet
#    restart: always
#    depends_on:
#      - tgbot
#    volumes:
#    - .:/src
#
#networks:
#  botnet:
#    driver: bridge
#  ignet:
#    driver: bridge